export const areaSubdivisions: Record<number, string[]> = {
  1: [
    "BIGLANG AWA",
    "VILLA FLORECIA",
    "DEL NACIA VILLE 3",
    "SAINT DOMINIC 9",
    "VICTORINO STREET",
  ],
  2: ["VILLA SABINA"],
  3: ["VILLILIA", "LATRINIDAD"],
  4: [
    "SILVINA VILLAGE",
    "SOLVILLE",
    "SAINT MARTIN VILLAGE",
    "CADAING VILLAGE",
    "MENDOZA",
  ],
  5: ["SAN AGUSTIN", "JEM 7", "GLORIA V"],
  6: [
    "GK STO NINO",
    "CANO CONCERNED",
    "ARTY SUBDIVISION",
    "PLEASANTVILLE",
    "CARREON",
  ],
  7: [
    "GISIS",
    "QUIRINO HIWAY",
    "511 INT",
    "517 INT",
    "MACAYA",
    "MACABALO",
    "CO2",
    "DRC",
    "GALGANA COMPD",
    "DEL NACIA DR",
    "DIANO COMP",
    "DEL MUNDO DR",
    "JP RAMOY",
    "GALGUERRA DR",
    "TANDANG SORA",
    "CARREON DR",
    "CAMPO 1",
    "CAMPO 2",
    "DULCE/GALVEZ CMP",
    "CONDO",
    "SHANATA",
    "THE AVENUE RESIDENCES",
    "MAGNOLIA PLACE",
    "NORTH BELTON",
    "CITIPLAZA",
  ],
};
